integrations/azuretfs/api/common.go
integrations/azuretfs/api/work_changelog.go
integrations/azuretfs/api/work_config.go
integrations/azuretfs/api/work_item.go
integrations/azuretfs/api/work_response_types.go

WIP - not ready for review or merging yet. Opening PR for visibility

APP-2739 Azure ids and mapping issues

---

Gopkg.lock
integrations/azuretfs/api/work_item.go
integrations/azuretfs/api/work_response_types.go

Needs https://github.com/pinpt/datamodel/pull/257

APP-2862 Added PR’s to issues

---

pkg/gitclone/git.go

- Update credentials for git clone folders
It happens that we use OAuth option to add an integration. The first time the agent will do a fresh git clone.
But then then we add the integration again using on-premise option and the first token we used expired, then we need to make sure we update the credentials every time because update the folders for incrementals.

APP-2891 Update git clone credentials

---

cmd/cmdservicerunnorestarts/inconfig/config.go
integrations/azuretfs/api/common.go
integrations/azuretfs/code_export.go
integrations/azuretfs/integration.go
integrations/azuretfs/work_export.go

Needs https://github.com/pinpt/datamodel/pull/260

APP-2907 Renamed Collection to CollectionName

---

cmd/cmdexport/sessions.go
pkg/expsessions/writer_dedup.go

https://pinpt-hq.atlassian.net/browse/APP-2857

Fix duplicate users issue in azure

---

Gopkg.lock
integrations/pkg/jiracommon/issues.go
integrations/pkg/jiracommonapi/issues.go

NOTE: this is only been ported to Jira. We need a separate port to Azure.  I wanted to get this working ASAP to unblock app team on updated to Project Dashboard and provide a clear way of how to do this as a template.
This PR resolves 2 issues:
- add support for pulling out the story point value (if found) for an issue
- add support for issue description
Since issue description will be displayed on the front-end, we're using the Jira HTML rendered version of the description and then cleaning it up (worked with Matt on what he wants for this) so that they can probably use it in the app.

DE-1850 DE-1870 story points + description

---

integrations/azuretfs/api/work_changelog.go
integrations/azuretfs/api/work_item.go
integrations/azuretfs/api/work_response_types.go

https://pinpt-hq.atlassian.net/browse/APP-2995

APP-2995 Azure Issue links

---

cmd/cmdservicerunnorestarts/updater/updater.go

APP-3039 bugfix: docker release downloads integrations, which are already present in image

APP-3039 skip integrations download if present in docker

---

integrations/azuretfs/api/common.go
integrations/azuretfs/api/work_changelog.go
integrations/azuretfs/api/work_config.go
integrations/azuretfs/api/work_issue.go
integrations/azuretfs/api/work_response_types.go

I still need to test with customer's data. Don't merge yet

AGT-5 Attempt to get the azure statuses and resoltions right

---

cmd/agent-dev/cmddownloadlogs/run.go
cmd/agent-dev/main.go

Use : 
```
go run ./cmd/agent-dev download-logs --url "URL" --user "USER" --password "PASS" --agent-uuid "UUID" --customer-id "CID" --len-records 150000
```

AGT-71 Added pagination to download-logs command

---

cmd/agent-dev/main.go
cmd/cmdintegration/integration.go

AGT-94 Agent does not call the right integrations if there are multiple

AGT-94 Agent does not call the right integrations if there are multiple

---

Gopkg.lock
cmd/agent-dev-mock-for-backend/enroll.go
cmd/agent-dev-mock-for-backend/run.go
cmd/agent-dev/test_backend_mock.go
cmd/cmdenroll/enroll.go
cmd/cmdexport/results.go
cmd/cmdrunnorestarts/cancel_events.go
cmd/cmdrunnorestarts/export_events.go
cmd/cmdrunnorestarts/integration_events.go
cmd/cmdrunnorestarts/onboarding_events.go
cmd/cmdrunnorestarts/uninstall_events.go
cmd/cmdrunnorestarts/update_events.go
integrations/bitbucket/api/pull_request.go
integrations/bitbucket/api/pull_request_comments.go
integrations/gitlab/api/pull_request_review.go

@josecordaz I got rid of ApprovedDate from gitlab, but not sure what it was doing before.

Updated integration-sdk

---

Gopkg.lock
integrations/jira/readme.md
integrations/pkg/jiracommon/issues.go
integrations/pkg/jiracommonapi/issue_comments.go
integrations/pkg/jiracommonapi/issues.go
pkg/ids/ids.go

Also fixes messed up id references, that had invalid order of ref_type vs ref_id.

DINT-132 Add jira comments

---

integrations/pkg/jiracommonapi/issues.go

the issue id is `customerID refID refType`

DE-2112 fix issue hashing#️⃣

---

integrations/github/_docs/exported_data.md
integrations/github/api/pull_request.go
integrations/github/api/pull_request_comment.go

fix issue where the pull request description and comments were using the stripped text instead of html which we need to render stuff like images and correctly format

DE-2139 fix pull request formatting of description and comments

---

cmd/agent-dev/main.go
cmd/cmdrun/run.go

Adjust restart resetFailuresAfter from 24h to 6h to better match our environment

Adjust restart resetFailuresAfter from 24h to 3h

---

Gopkg.lock

Revert "DINT-188 Updated ripsrc"

---

Gopkg.lock
cmd/cmdrunnorestarts/exporter/exporter.go
cmd/cmdrunnorestarts/exporter/exporter_test.go
cmd/cmdrunnorestarts/inconfig/config.go
cmd/cmdrunnorestarts/inconfig/config_test.go
cmd/cmdrunnorestarts/inconfig/def.go

Revert "DINT-191 Merge integrations created by the same user"

---

Gopkg.lock

tested with export. 
story_points in work.Issue should have nulls in the output (in addition to values)

DE-2217 fixed where empty story_points have 0 value

---

cmd/cmdvalidateconfig/validate.go

This fixes an error message in log.

Do not use fmt to log

---

pkg/fsconf/fsconf.go

bump the state version to 5 to force historical on new release and move to top and const to make it easier for the future

state bump

---

pkg/fsconf/fsconf.go

Revert "bump state to force historical"

---

integrations/bitbucket/_docs/exported_data.md
integrations/bitbucket/api/pull_request_commits.go

https://pinpt-hq.atlassian.net/browse/TEA-62

TEA-62 bitbucket: remove PullRequestCommit:Additions, it's too slow

---

Gopkg.lock
integrations/github/api/pull_request.go
integrations/gitlab/api/pullrequest.go

Dear @rblalock,
We had a conversation over Slack about how to show old PRs in the app. You said it would be good to have Draft status as well.
Because it's the weekend and I'm waiting on a build to finish and I love you so much. I just added it for you.  I hope this makes your heart skip a beat.
♥️
Jeff

TIGR-264 add support for Draft on PullRequests and fixed Locked status as well

---

slimrippy/exportrepo/exportrepo.go

I replicated the logic from here https://github.com/pinpt/agent/blob/master/integrations/github/commit_users.go#L126

PROD-576 Skip users with no name or no email

---

integrations/github/api/webhook_registration.go

this will make sure that the agent doesnt remove the webhook url from our new agent

dont remove webhook if it has v4 integration_id param

---

integrations/gitlab/api/pull_request_comment.go
integrations/gitlab/api/pull_request_review.go
integrations/gitlab/api/pullrequest.go
integrations/gitlab/api/user.go

Fixed user_ref_id for:
- pullrequests
- pullrequest_reviews
- pullrequest_comments

GOLD-123 Fixed user_ref_id
